### PR TITLE
various fixes

### PR DESCRIPTION
**Pull request by FabianFrank**
1. upgrade device catalog
2. fix a php error log causing missing check
3. fix a compiler warning on iOS that prevents pod spec lint

### CODE REVIEW

**Comment by DerAndereAndi** [comment]
Thanks for these Fabian!

**Comment by DerAndereAndi** [comment]
Oh, I just saw you are merging to master, I would prefer to use develop, since master is release only. Could you change that or should I do a manual merge?

**Comment by FabianFrank** [comment]
@TheRealKerni develop is behind master, is this intentional? if so, I can submit a PR with only these 3 commits against develop.

**Comment by DerAndereAndi** [comment]
The master branch is not behind, latest release was on 25th March 2012 :) Btw. feel free to add a pull request for removing that PHP-JSON "hack" for older PHP releases. I have no problems removing it :)

**Comment by FabianFrank** [comment]
I will open a new one for this later.

**Pull request closed without merging**
