### PR TITLE
Fixed bug with parsing iOS plist information.

### PR DESCRIPTION
**Pull request by pekalicious**
App name and version was not showing correctly for IPAs because the array was not in the format the code was assuming.

Current:
$newApp[self::INDEX_APP]            = $parsed_plist['items'][0]['metadata']['title'];

Correct:
$newApp[self::INDEX_APP]            = $parsed_plist['title'];

### CODE REVIEW

**Comment by DerAndereAndi** [comment]
Hi,

according to the plist files I have, our code is correct and works. The plist contains an array with the key `items`, and the first element in that array contains another key `metadata`. So our code looks correct.

How did you generate your plist that this is different now?
Andreas

**Comment by pekalicious** [comment]
I see. I used the Info.plist that was generated by Unity as a template. I wrongly assumed that all plists are structured the same. I'll cancel this pull request.

**Comment by DerAndereAndi** [comment]
Yes, these are different files. The info.plist is needed inside the created .app package. The distribution plist file (app manifest) is of a different structure and usually created using the Xcode organizer when creating an ipa file for OTA distribution. You can find the documentation of the generated plist file here: http://help.apple.com/iosdeployment-apps/mac/1.1/#app43ad78b3

**Comment by pekalicious** [comment]
Aha! Thank you very very much for this! 

I am trying to automate the entire build process and I don't use xcode GUI at all, so I didn't know how to find that plist. I use Apache Ant to call Unity that will produce the xcode project, then call xcodebuild to build that project and then xcrun to package the IPA. 

I don't know how to produce the manifest plist from command line.

**Comment by DerAndereAndi** [comment]
Check this wiki page: https://github.com/TheRealKerni/HockeyKit/wiki/Build-Automatization

**Comment by pekalicious** [comment]
That is amazing! Thank you very very much! I'll look into it right away.

**Pull request closed without merging**
